service: serverless-httpadapterbug

plugins:
 - serverless-plugin-typescript
 - serverless-plugin-optimize

package:

custom:
 optimize:
  external: ['@nestjs/graphql']
  externalPaths:
   '@nestjs/graphql': 'node_modules/@nestjs/graphql'
 myStage: ${opt:stage, self:provider.stage}
 myEnvironment:
  NODE_ENV:
   prod: "production"
   dev: "development"

provider:
 name: aws
 runtime: nodejs12.x
 region: eu-central-1
 memorySize: 512
 environment:
  NODE_ENV: ${self:custom.myEnvironment.NODE_ENV.${self:custom.myStage}}
  NODE_TLS_REJECT_UNAUTHORIZED: '0'

functions:
 main: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: src/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}
